### ISSUE TITLE
brosel build fail mojave  -   platypus 5.4.1

### ISSUE THREAD

**Issue by sqeeezy** [halloleo/brosel#1]
hello, late 2013 13" retina MacBook Pro with macos 10.14.6 using MacPorts to install Platypus 5.4.1, I get the following fail

/Users/nik/Downloads/brosel-master> ls
DEBUG LICENSE README.md brosel.platypus brosel.py brosel.yaml yaml
/Users/nik/Downloads/brosel-master> platypus -P brosel.platypus /Applications/brosel.app
Warning: Profile created with different version of Platypus.
Error: Executable binary not found at path '/usr/local/share/platypus/ScriptExec'
/Users/nik/Downloads/brosel-master> platypus -v
platypus version 5.4.1
/Users/nik/Downloads/brosel-master>

I'm not very clever so it's probably a stupid mistake I'm making. Thanks in advance. Obviously my binaries are in /opt/local/bin the MacPorts default location.

**Comment by halloleo** [comment]
Thanks for raising this.

I think Platypus profiles aren't backwarrds compatible. I use Platypus 5.2. So with a never version of Platypus, create your own profile. I now have noted the version requirement in the ReadMe.

Furthermore I do not maintain this tool further and will archive the repository.
